print('===== DESAFIO 03 =====')
print('Olá, seja bem-vindo ao nosso programa!')
print('Aqui você poderá saber o dobro, o triplo e a raiz quadrada de qualquer número inteiro que você escolher"')
n1 = int(input('Para isso, digite qualquer número inteiro a seguir: '))
print(f'Ótimo! O número escolhido foi: {n1}.')
print(f'O dobro de {n1} é: {n1*2}.')
print(f'O triplo de {n1} é: {n1*3}.')
print(f'E a raiz quadrada de {n1} é: {n1**(1/2)}.')
print('Obrigado por usar o nosso programa!')
