print('===== DESAFIO 06 =====')
print('Olá! Seja bem vindo ao nosso programa de tabuada online!')
print('Aqui você poderá escolher qualquer número e o nosso programa fará a simulação de uma tabuada com o número escolhido!')
nm = int(input('Para darmos início, por favor, digite um número inteiro a seguir: '))
print(f'Ótimo, o número escolhido foi: {nm}.')
print(f'A seguir, está a tabuada com o número escolhido: ')
print(f'0x{nm} = {nm*0}')
print(f'1x{nm} = {nm*1}')
print(f'2x{nm} = {nm*2}')
print(f'3x{nm} = {nm*3}')
print(f'4x{nm} = {nm*4}')
print(f'5x{nm} = {nm*5}')
print(f'6x{nm} = {nm*6}')
print(f'7x{nm} = {nm*7}')
print(f'8x{nm} = {nm*8}')
print(f'9x{nm} = {nm*9}')
print(f'10x{nm} = {nm*10}')
print('Obrigado por usar a nossa calculadora!')
