print('===== DESAFIO 04 =====')
print('Olá, seja bem-vindo ao nosso programa!')
print('Aqui, você poderá atribuir duas notas a um aluno e calcular a média das notas atribuídas.')
nome = str(input('Antes de iniciarmos, escolha um nome para o aluno: '))
nota1 = float(input(f'Ótimo! Agora, atribua a primeira nota do aluno {nome}: '))
nota2 = float(input('Agora, escolha a segunda nota: '))
print(f'Muito bem, a primeira nota atribuída ao aluno {nome} foi de: {nota1}, e a segunda foi de {nota2}.')
print(f'Logo, a média das duas notas escolhidas é de: {(nota1+nota2)/2:.2f}')
print('Obrigado por usar o nosso programa!')
