print('===== DESAFIO 08 =====')
print('Olá, seja bem-vindo ao nosso programa!')
print('Aqui você poderá calcular o total de litros de tinta necessário para pintar uma determinada área desejada.')
print('Haja vista que cada litro de tinta pode pintar uma área equivalente a 2 metros quadrados.')
largura = float(input('Para iniciarmos, digite a largura da área a ser pintada, em metros: '))
comprimento = float(input('Agora, digite o comprimento da área a ser pintada, em metros: '))
print(f'Ótimo, a área total a ser pintada é de: {largura*comprimento} metros quadrados.')
print(f'Logo, o total de litros de tinta necessário para pintar uma área de {largura*comprimento} será de {(largura*comprimento)/2} litros.')
print('Obrigado por usar o nosso programa.')
