print('===== DESAFIO 05 =====')
print('Olá, seja bem vindo ao nosso programa!')
print('Aqui,você terá acesso a uma eficiente calculadora de conversão de unidades de medida!')
print('Para usá-la, basta inserir um valor em metros e a calculadra irá mostrar a medida em centímetros e milímetros!')
valor = float(input('Para começarmos, digite um valor qualquer a seguir em metros: '))
print(f'Ótimo, o valor escolhido foi de: {valor} metros.')
print(f'Em centímetros, o valor é de: {valor*100} cm.')
print(f'E em milímetros, o valor ficará: {valor*1000} mm.')
print('Obrigado por usar a nossa calculadora de conversão de unidades de medida!')
